### ISSUE TITLE
cannot print chinese by roslog

### ISSUE THREAD

**Issue by DinnerHowe** [ros/console_bridge#49] opened 2017-12-06 09:34 UTC
hi, there:
     We found ROS cannot print Chinese by c++, like" 我是新手 ".
     For instance, ROS_INFO(" 我是新手 "), the result is [ INFO] [1512552131.271037807]: ????????????
     However, in python ROS could print Chinese well.
     Is this issue caused by pointer? 
     like: const char* m in void console_bridge::log(const char *file, int line, LogLevel level, const char* m, ...)
@wjwwood

**Comment by scpeters** [comment] 2017-12-06 17:21
maybe we need to use `std::wstring` in the API?

**Comment by DinnerHowe** [comment] 2017-12-12 03:44
yes, i think so.
also, i tried input a wstring to ROS_INFO, it cannot pass catkin make yet:

```
    std::wstring aa;
    aa = "我是新手";
    ROS_INFO(aa);
```
the error is 
`error: invalid conversion from ‘const char*’ to ‘wchar_t’ [-fpermissive]`

**Comment by rjosodtssp** [comment] 2018-11-07 07:21
Anyone knows solution ?

**Comment by scpeters** [comment] 2018-11-07 19:46
I just added a small test case in console_bridge to print Chinese characters, and it appears to work for me: https://github.com/scpeters/console_bridge/commit/2c95bdd6f335178d960603fdd0116ecf685978d8

Perhaps the problem is farther downstream in ROS?

**Comment by scpeters** [comment] 2018-11-07 19:47
https://travis-ci.org/scpeters/console_bridge/jobs/452058400#L526

**Comment by wjwwood** [comment] 2018-11-07 19:49
`rosout` sends the logs as an ascii string in the topics, see:

https://github.com/ros/ros_comm_msgs/blob/bfb8533fd6c6e959c71f0d2a9669baeff2dac1ad/rosgraph_msgs/msg/Log.msg#L15

I do not believe this can be fixed because ROS 1's type system doesn't support wide strings.

Will support them in ROS 2 though, so maybe we should put that (should support unicode messages) as input to the ongoing work for the logging subsystem in ROS 2:

https://discourse.ros.org/t/ros2-logging/6469

**Comment by scpeters** [comment] 2018-11-07 19:59
thanks @wjwwood 

I added a comment that we should support this in ros2

I will close this issue since it is not a problem with console_bridge

**Closed by scpeters** 2018-11-07 19:59 UTC
